# Gateway Service application.yml
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "X-Requested-With"
              - "Access-Control-Request-Method"
              - "Access-Control-Request-Headers"
            exposedHeaders:
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: catalog-service-product
          uri: http://catalog-service:8081
          predicates:
            - Path=/api/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: catalog-service-category
          uri: http://catalog-service:8081
          predicates:
            - Path=/api/categories/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: invoice-service
          uri: http://invoice-service:8083
          predicates:
            - Path=/api/invoices/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Credentials, true
server:
  port: 8080